spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  profiles:
    active: dev
  config:
    import: "optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: triage-route
          uri: lb://triage-service
          predicates:
            - Path=/triage/**
          filters:
            - StripPrefix=1

        - id: appointment-route
          uri: lb://appointment-service
          predicates:
            - Path=/appointment/**
          filters:
            - StripPrefix=1

        - id: medical-record-route
          uri: lb://medical-record-service
          predicates:
            - Path=/medical-record/**
          filters:
            - StripPrefix=1

        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://keycloak:8080/realms/sus-connect}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://keycloak:8080/realms/sus-connect/protocol/openid-connect/certs}

server:
  port: 8761
  error:
    include-stacktrace: never
    include-message: always

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8762/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    root: INFO
    br.com.fiap.gateway: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId:-}] [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always
